services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        container_name: hw-app
        working_dir: /var/www/html
        ports:
            - "8081:8080"
        depends_on:
            - mysql
            - redis
            - mqtt
        environment:
            DB_HOST: mysql
            REDIS_HOST: redis
            MQTT_HOST: mqtt
        networks:
            - HydroWatch

    mqtt-listener:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        container_name: hw-mqtt-listener
        working_dir: /var/www/html
        command: php artisan mqtt:listen
        depends_on:
            - app
            - mqtt
            - mysql
        environment:
            DB_HOST: mysql
            REDIS_HOST: redis
            MQTT_HOST: mqtt
        networks:
            - HydroWatch

    mysql:
        image: mysql:8.0
        container_name: hw-mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: hydrowatch
        volumes:
            - hydrowatch_mysql_data:/var/lib/mysql
        ports:
            - "3312:3306"
        networks:
            - HydroWatch

    redis:
        image: redis:alpine
        container_name: hw-redis
        restart: always
        volumes:
            - hydrowatch_redis_data:/data
        networks:
            - HydroWatch

    mqtt:
        image: eclipse-mosquitto:2
        container_name: hw-mqtt
        restart: always
        volumes:
            - ./docker/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
            - hydrowatch_mqtt_data:/mosquitto/data
        ports:
            - "1883:1883"
        networks:
            - HydroWatch

volumes:
    hydrowatch_mysql_data:
    hydrowatch_redis_data:
    hydrowatch_mqtt_data:

networks:
    HydroWatch:
        driver: bridge
