services:
  app:
    restart: unless-stopped
  mysql:
    restart: unless-stopped
  redis:
    restart: unless-stopped
    ports:
      - "6382:6379"
  mqtt:
    restart: unless-stopped
  mqtt-listener:
    restart: unless-stopped
